---
- name: Running workload provision tasks
  when: ACTION | default('provision') == 'provision'
  ansible.builtin.include_tasks: workload.yml

- name: Running workload removal tasks
  when: ACTION | default('provision') == 'destroy'
  ansible.builtin.include_tasks: remove_workload.yml
